services:
  - docker:dind

stages:
  - build
  - dockerize
  - deploy

variables:
  DOCKER_DRIVER: overlay2


build:
  stage: build
  image: golang
  script:
    - go mod vendor
    - go build -o ${CI_PROJECT_DIR}/pipestarter pipestarter.go
    - ls  ${CI_PROJECT_DIR}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/pipestarter
    expire_in: 20 min
  only:
    - tags
  tags:
    - devops

dockerize:
  stage: dockerize
  image: docker:latest
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    IMAGE_TAG: "$CI_COMMIT_TAG"
    MAIL_PASS: $EMAIL_PASS
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - ls
    - docker build  --build-arg MAIL_PASS=$MAIL_PASS --tag $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:latest
  only:
    - tags
  tags:
    - devops
